### ISSUE TITLE
Результат применения фильтров(город+услуга) выводит все компании в выбранном городе, когда по указанным фильтрам нет совпадений

### ISSUE THREAD

**Issue by GretaGerber** [Information-platform-about-IT-companies/Qase_bugs#235]
Severity Minor
Priority Low
**Шаги:**

1. Открыть веб-приложение: https://dev.octopus-it.ru/
2. Нажать кнопку "Посмотреть все компании"
3. Меню фильтра Город выбрать Ижевск
4. В меню фильтра Услуги UX/UI-дизайн

**Фактический результат:**
Выводит все компании города Ижевска
**Ожидаемый результат:**
Если по указанным фильтрам ничего не найдено - Переводит на страницу сортировки с компаниями, которые оказывают такие же услуги
**Окружение:**
OC: Windows 11 Домашняя, 22H2,
Google Chrome Версия 119.0.6045.200. Разрешение: 1920*1080
![Recording #6](https://github.com/Information-platform-about-IT-companies/Qase_bugs/assets/118084771/378028b3-7402-4ce1-8694-139d1710ef6c)
https://app.qase.io/defect/OCTOPUS/view/200

**Comment by ArturKhelshtein** [comment]
поправлено

**Comment by qavero** [comment]
PASSED
